### ISSUE TITLE
Cookies don't get rewritten properly under subdomains

### ISSUE THREAD

**Issue by mateusz-pocztowski** [the-heart-rnd/http-proxy#17]
## Description
I configured `http-proxy` rule to rewrite cookies for a subdomain as follows:
```
{
  "match": {
    "path": "/path"
  },
  "target": "https://subdomain.example.com/path",
  "response": {
    "cors": "referer",
    "rewrite": {
      "cookie": true,
      "rebase": true
    }
  }
}
```
I'd expect a response with cookie `Domain=example.com;` get rewritten to the proxy host (localhost). 

## Possible Solution
I think `http-proxy` should extract domain from the `set-cookie` response header. Currently, it matches domains by rule target's hostname (`subdomain.example.com` in my case), so it won't match if rule's target contains subdomain.

**Comment by HitoriSensei** [comment]
I'm attaching relevant RFCs describing cookie mechanisms to be implemented and tested against.
https://datatracker.ietf.org/doc/html/rfc2109
https://datatracker.ietf.org/doc/html/rfc6265

**Comment by HitoriSensei** [comment]
@mateusz-pocztowski could you check your case against branch [17-cookies-dont-get-rewritten-properly-under-subdomains](https://github.com/the-heart-rnd/http-proxy/tree/17-cookies-dont-get-rewritten-properly-under-subdomains) ?

**Comment by mateusz-pocztowski** [comment]
@HitoriSensei It works :)
